config/routes.rb
Rails.application.routes.draw do
  root to: 'seats#index'
  resource :seats, only: [:update]
  get '/seats', to: 'seats#index'
  get '/seats/validate', to: 'seats#validate'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  def is_booked?
    return self.booked
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  def index
  end

  def update
    block = params[:block].to_s.downcase
    row = params[:row].to_i
    first_seat = params[:first_seat].to_i
    last_seat = params[:last_seat].to_i
    first_name = params[:first_name].to_s
    last_name = params[:last_name].to_s
    email = params[:email].to_s
    contact = params[:contact].to_i

    seats = find_seats(block, row, first_seat, last_seat)
    unless customer = Customer.find_by(email: email)
      customer = Customer.create(first_name: first_name, last_name: last_name, email: email, contact: contact)
      seats.each do |seat|
        seat.update_attributes(customer_id: customer.id, booked: true) unless seat.booked?
      end
      # CustomerMailer.booking_confirmation(customer).deliver_now
    end

    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def validate
    block = params[:block].to_s.downcase
    row = params[:row].to_i
    first_seat = params[:first_seat].to_i
    last_seat = params[:last_seat].to_i

    @booked_seats = []
    seats = find_seats(block, row, first_seat, last_seat)
    seats.each do |seat|
      @booked_seats.push(seat.column) if seat.booked?
    end
    @booked_seats = @booked_seats.join(", ")

  end
  def find_seats(block, row, seat_1, seat_2)
    seats = []
    (seat_1..seat_2).each do |seat_num|
      seat = Seat.find_by(block: block, row: row, column: seat_num)
      seats.push(seat) unless seats.include? seat
    end
    seats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
  def find_rows(blk)
    rows = []
    Seat.where(block: blk).each do |seat|
      rows.push(seat.row) unless rows.include? seat.row
    end
    rows[]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Booking System
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.menu_red
      .container
        .nav-wrapper
          %a.brand-logo{href: root_path } Booking System
          %ul.right
            %li
              %a{href: root_path } Home
            %li
              %a{href: '#'} Login
            %li
              %a{href: seats_path} Book Seats

    .container
      .spacer
      = yield

app/views/seats/index.html.haml
.row
  .col.m12.l6.offset-l3
    .card.brown_color.z-depth-2
      .card-content.white-text
        %h4.center Enter Seat & Contact Details
        .seat_form
          .row
            .input-field.col.s12
              %input#seat_block.validate{type: "text"}
              %label{for: "seat_block"} Block
            .input-field.col.s12
              %input#seat_row.validate{type: "text"}
              %label{for: "seat_row"} Row
          .row
            .input-field.col.s6
              %input#seat_column_1.validate{type: "text"}
              %label{for: "seat_column_1"} First Seat
            .input-field.col.s6
              %input#seat_column_2.validate{type: "text"}
              %label{for: "seat_column_2"} Last Seat
        .seat_form_2
          .row
            .input-field.col.m12.l6
              %input#first_name.validate{type: "text"}
              %label{for: "seat_block"} First Name
            .input-field.col.m12.l6
              %input#last_name.validate{type: "text"}
              %label{for: "seat_row"} Last Name
          .row
            .input-field.col.s12
              %input#email.validate{type: "email"}
              %label{for: "seat_column_1"} Email
            .input-field.col.s12
              %input#contactno.validate{type: "tel"}
              %label{for: "seat_column_2"} Contact No.
        .spacer
        .row
          .center
            .btn#validate.tooltipped{"data-delay" => "50", "data-position" => "bottom", "data-tooltip" => "Validate if Seats are available"}
              %i.material-icons event_seat
            .btn#save
              %i.material-icons keyboard_arrow_right

:coffeescript
  $(document).ready ->
  $("select").material_select()
  $(".seat_form_2").hide()
  secondform = false
  $("#save").click ->
    if secondform == false
      $(".seat_form").fadeOut "slow", "easeInOutQuad", ->
        $(".seat_form_2").fadeIn "slow", "easeInOutQuad"
        $("#save .material-icons").replaceWith "<i class=\"material-icons\">done</i>"
        secondform = true
        return
    else
      $.ajax
        type: "PATCH"
        url: "#{seats_path}"
        data:
          block: $("#seat_block").val()
          row: $("#seat_row").val()
          first_seat: $("#seat_column_1").val()
          last_seat: $("#seat_column_2").val()
          first_name: $("#first_name").val()
          last_name: $("#last_name").val()
          email: $("#email").val()
          contact: $("#contactno").val()
        dataType: "script"
    return
  $("#validate").click ->
    $.ajax
      type: "GET"
      url: "#{seats_validate_path}"
      data:
        block: $("#seat_block").val()
        row: $("#seat_row").val()
        first_seat: $("#seat_column_1").val()
        last_seat: $("#seat_column_2").val()
      dataType: "script"
  return

app/views/seats/validate.js.erb
if ("<%= escape_javascript(@booked_seats) %>" == ""){
  alert("All the selected seats are Available")
}else{
  alert("The following seats are not available : <%= escape_javascript(@booked_seats) %>")
}